### ISSUE TITLE
SpamSum/ESS comparison (feature)

### ISSUE THREAD

**Issue by retrography** [tdebatty/java-spamsum#1]
Any plan to include the simhash comparison in the package? I already have something [here](https://github.com/retrography/JessDeep/blob/master/src/main/java/SpamSumSignature.java) to start with, but it has substantial redundancy with your work, so it needs to be simplified. Btw, that `editDistance` function in my coed is not needed if you are willing to add a dependency (Apache's StringUtils).

**Comment by tdebatty** [comment]
Hi,
Sorry for the late anwser :-/
I really like your idea, and I'll try to implement it today...

**Comment by retrography** [comment]
Hi Thibault,

I got the time to test my code a couple of days ago, and I noticed it
doesn't work as expected. If you are working on it today, make sure you
troubleshoot it first. If not, I will let you know when I get to do so.

As far as I know there is no good spamsum package in pure Java, so it is
interesting and useful what you are doing.

Mahmood

## 

Mahmood Shafeie Zargar
Sent with Airmail

**Comment by tdebatty** [comment]
Hi,
Just finished the implementation and released a new version on Maven (should be available on Maven central within a few hours).
I only tested with a few files. Maybe it would be interesting to add more files to perform tests...

**Comment by retrography** [comment]
Nice! 

But dude, you have removed all copyright notices. Apache requires you to give proper attribution. Plus some credit would be appreciated for the Java translation! ;)

**Comment by tdebatty** [comment]
Hi!

You're right. I just cleaned the code a little and added references to the
origins...

Best regards,
